import React, { useState } from 'react';
import { motion } from 'framer-motion';
import {
  ArrowLeft,
  CheckCircle2,
  Lock,
  Sparkles,
  MessageSquare,
  FileCode2,
  FileText,
  Shield,
  Clock,
  Send,
  Copy,
  Check,
  Zap,
  Download,
  Trash2,
} from 'lucide-react';
import { StatusBadge } from '../components/StatusBadge';
import { api } from '../api/client';

export function Investigation({ data, user, onBack, onRefresh }) {
  const { case: incident, clues = [], found = [], comments = [] } = data;
  const [activeTab, setActiveTab] = useState('clues');
  const [newComment, setNewComment] = useState('');
  const [unlockingId, setUnlockingId] = useState(null);
  const [isPostingComment, setIsPostingComment] = useState(false);
  const [copiedId, setCopiedId] = useState(null);
  const [isUpdatingStatus, setIsUpdatingStatus] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);
  const [postmortemCopied, setPostmortemCopied] = useState(false);

  const isCompleted = clues.length > 0 && found.length === clues.length;
  const progressPercent = clues.length ? Math.round((found.length / clues.length) * 100) : 0;
  const canDelete = user?.role === 'ADMIN' || (user?.id && user?.id === incident.created_by);

  const handleUnlockClue = async (clueId) => {
    if (found.includes(clueId) || unlockingId !== null) return;
    setUnlockingId(clueId);
    try {
      await api.post(`/cases/${incident.id}/clues/${clueId}/unlock`);
      await onRefresh();
    } catch (err) {
      console.error('Failed to unlock clue', err);
    } finally {
      setUnlockingId(null);
    }
  };

  const handleUpdateStatus = async (newStatus) => {
    if (incident.status === newStatus || isUpdatingStatus) return;
    setIsUpdatingStatus(true);
    try {
      await api.patch(`/cases/${incident.id}/status`, { status: newStatus });
      await onRefresh();
    } catch (err) {
      console.error('Failed to update status', err);
    } finally {
      setIsUpdatingStatus(false);
    }
  };

  const handleDeleteCase = async () => {
    if (!window.confirm(`Are you sure you want to delete incident INC-${String(incident.id).padStart(3, '0')} (${incident.title})?`)) {
      return;
    }
    setIsDeleting(true);
    try {
      await api.delete(`/cases/${incident.id}`);
      onBack();
    } catch (err) {
      console.error('Failed to delete incident', err);
      alert(err.response?.data?.message || 'Failed to delete incident');
      setIsDeleting(false);
    }
  };

  const handleAddComment = async (e) => {
    e.preventDefault();
    if (!newComment.trim() || isPostingComment) return;
    setIsPostingComment(true);
    try {
      await api.post(`/cases/${incident.id}/comments`, { content: newComment.trim() });
      setNewComment('');
      await onRefresh();
    } catch (err) {
      console.error('Failed to post comment', err);
    } finally {
      setIsPostingComment(false);
    }
  };

  const copyToClipboard = (text, id) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  const generatePostmortemMarkdown = () => {
    const formattedId = `INC-${String(incident.id).padStart(3, '0')}`;
    const dateStr = incident.created_at || new Date().toISOString();

    return `# Incident Postmortem: ${formattedId} — ${incident.title}

- **Date**: ${dateStr}
- **Severity**: ${incident.severity}
- **Current Status**: ${incident.status}
- **Environment**: ${incident.environment || 'Production'}
- **Category**: ${incident.category || 'Backend'}
- **Tech Stack**: ${incident.language || 'N/A'} / ${incident.framework || 'N/A'}
- **Search Tags**: ${incident.tags || 'none'}

---

## 1. Executive Summary
${incident.description}

---

## 2. Root Cause Analysis (RCA)
${incident.root_cause || 'Root cause under investigation.'}

---

## 3. Evidence & Telemetry Findings (${found.length}/${clues.length} Discovered)
${
  clues.length > 0
    ? clues
        .map(
          (c, idx) => `### Layer ${idx + 1}: ${c.title}
- **Description**: ${c.description}
- **Telemetry Evidence**:
\`\`\`
${found.includes(c.id) && c.evidence ? c.evidence : '[Evidence encrypted or pending investigation]'}
\`\`\`
`
        )
        .join('\n')
    : 'No evidence clues logged for this incident.'
}

---

## 4. Remediation & Prevention Strategy
${incident.solution || 'Remediation guidelines pending review.'}

---

## 5. Investigation Notes & Field Log (${comments.length} entries)
${
  comments.length > 0
    ? comments
        .map((comm) => `- **[${comm.created_at || 'Log'}] ${comm.name || 'Investigator'}**: ${comm.content}`)
        .join('\n')
    : 'No investigation field notes logged.'
}

---
*Generated by BugAtlas Incident Investigation Platform*
`;
  };

  const handleCopyPostmortem = () => {
    const text = generatePostmortemMarkdown();
    navigator.clipboard.writeText(text);
    setPostmortemCopied(true);
    setTimeout(() => setPostmortemCopied(false), 2000);
  };

  const handleDownloadPostmortem = () => {
    const text = generatePostmortemMarkdown();
    const blob = new Blob([text], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `INC-${String(incident.id).padStart(3, '0')}-postmortem.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="page-container">
      {/* Back navigation */}
      <button className="btn-back" onClick={onBack}>
        <ArrowLeft size={14} />
        <span>Incident Board</span>
        <span className="breadcrumb-slash">/</span>
        <span className="active-case-num">INC-{String(incident.id).padStart(3, '0')}</span>
      </button>

      {/* Incident Hero Banner */}
      <div className="investigation-hero">
        <div className="hero-main">
          <div className="hero-badges">
            <span className="incident-id-tag">INC-{String(incident.id).padStart(3, '0')}</span>
            <StatusBadge severity={incident.severity} />
            <StatusBadge status={incident.status} />
          </div>
          <h1 className="hero-title">{incident.title}</h1>
          <p className="hero-description">{incident.description}</p>

          <div className="hero-meta-pills">
            {incident.environment && <span className="meta-pill">Env: {incident.environment}</span>}
            {incident.category && <span className="meta-pill">Cat: {incident.category}</span>}
            {incident.language && <span className="meta-pill">Lang: {incident.language}</span>}
            {incident.framework && <span className="meta-pill">Stack: {incident.framework}</span>}
          </div>

          <div className="hero-status-actions">
            <div className="status-lifecycle-group">
              <span className="status-lifecycle-label">Incident State:</span>
              {['OPEN', 'INVESTIGATING', 'RESOLVED'].map((st) => (
                <button
                  key={st}
                  type="button"
                  className={`btn-status-pill ${st.toLowerCase()} ${incident.status === st ? 'active' : ''}`}
                  onClick={() => handleUpdateStatus(st)}
                  disabled={isUpdatingStatus}
                >
                  {st === 'RESOLVED' && <CheckCircle2 size={12} />}
                  <span>{st}</span>
                </button>
              ))}
            </div>

            {canDelete && (
              <button
                type="button"
                className="btn-delete-case"
                onClick={handleDeleteCase}
                disabled={isDeleting}
                title="Delete this incident"
              >
                <Trash2 size={13} />
                <span>Delete</span>
              </button>
            )}
          </div>
        </div>

        {/* Progress Tracker Card */}
        <div className="investigation-progress-card">
          <div className="progress-card-header">
            <span className="progress-card-title">Investigation Progress</span>
            <span className="progress-card-percent">{progressPercent}%</span>
          </div>
          <div className="progress-track-lg">
            <div
              className={`progress-fill-lg ${isCompleted ? 'completed' : ''}`}
              style={{ width: `${progressPercent}%` }}
            />
          </div>
          <div className="progress-card-footer">
            <span>
              {found.length} of {clues.length} evidence points isolated
            </span>
            {isCompleted && (
              <span className="status-complete-pill">
                <CheckCircle2 size={12} /> Root Cause Isolated
              </span>
            )}
          </div>
        </div>
      </div>

      {/* Navigation Tabs */}
      <div className="investigation-tabs">
        <button
          className={`tab-btn ${activeTab === 'clues' ? 'active' : ''}`}
          onClick={() => setActiveTab('clues')}
        >
          <FileCode2 size={15} />
          <span>Evidence & Clues</span>
          <span className="tab-counter">
            {found.length}/{clues.length}
          </span>
        </button>

        <button
          className={`tab-btn ${activeTab === 'rca' ? 'active' : ''}`}
          onClick={() => setActiveTab('rca')}
        >
          <Shield size={15} />
          <span>Root Cause & Profile</span>
        </button>

        <button
          className={`tab-btn ${activeTab === 'discussion' ? 'active' : ''}`}
          onClick={() => setActiveTab('discussion')}
        >
          <MessageSquare size={15} />
          <span>Incident Notes</span>
          <span className="tab-counter">{comments.length}</span>
        </button>

        <button
          className={`tab-btn ${activeTab === 'postmortem' ? 'active' : ''}`}
          onClick={() => setActiveTab('postmortem')}
        >
          <FileText size={15} />
          <span>Postmortem Report</span>
        </button>
      </div>

      {/* Tab: Evidence & Clues */}
      {activeTab === 'clues' && (
        <div className="tab-content">
          {/* Completion Callout */}
          {isCompleted && (
            <motion.div
              className="root-cause-banner"
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
            >
              <div className="banner-icon-box">
                <Sparkles size={20} />
              </div>
              <div className="banner-text">
                <h3 className="banner-title">Root Cause File Unlocked</h3>
                <p className="banner-desc">
                  <strong>Identified Cause:</strong> {incident.root_cause || 'Root cause identified.'}
                </p>
                {incident.solution && (
                  <p className="banner-solution">
                    <strong>Remediation:</strong> {incident.solution}
                  </p>
                )}
                {incident.status !== 'RESOLVED' && (
                  <div className="banner-action-resolve" style={{ marginTop: '12px' }}>
                    <button
                      type="button"
                      className="btn btn-primary btn-sm"
                      onClick={() => handleUpdateStatus('RESOLVED')}
                      disabled={isUpdatingStatus}
                    >
                      <Sparkles size={14} />
                      <span>{isUpdatingStatus ? 'Resolving Case...' : 'Mark Incident as RESOLVED (+100 XP)'}</span>
                    </button>
                  </div>
                )}
              </div>
            </motion.div>
          )}

          <div className="clues-grid">
            {clues.map((clue, idx) => {
              const isFound = found.includes(clue.id);
              const isBusy = unlockingId === clue.id;

              return (
                <div
                  key={clue.id}
                  className={`clue-card ${isFound ? 'unlocked' : 'locked'}`}
                >
                  <div className="clue-card-header">
                    <span className="clue-number">LAYER {String(idx + 1).padStart(2, '0')}</span>
                    <span className="clue-reward">+{clue.xp_reward} XP</span>
                  </div>

                  <div className="clue-body">
                    <h3 className="clue-title">{isFound ? clue.title : 'Encrypted Evidence'}</h3>
                    <p className="clue-desc">
                      {isFound
                        ? clue.description
                        : 'Examine this layer to uncover logs, network requests, or stack trace telemetry.'}
                    </p>

                    {isFound && clue.evidence && (
                      <div className="evidence-code-block">
                        <div className="code-header">
                          <span className="code-label">TELEMETRY / LOG EVIDENCE</span>
                          <button
                            className="btn-copy-code"
                            onClick={() => copyToClipboard(clue.evidence, clue.id)}
                            title="Copy to clipboard"
                          >
                            {copiedId === clue.id ? <Check size={12} /> : <Copy size={12} />}
                          </button>
                        </div>
                        <pre className="code-content">{clue.evidence}</pre>
                      </div>
                    )}
                  </div>

                  <div className="clue-footer">
                    {isFound ? (
                      <div className="clue-status-unlocked">
                        <CheckCircle2 size={14} />
                        <span>Evidence Discovered</span>
                      </div>
                    ) : (
                      <button
                        className="btn btn-primary btn-sm btn-block"
                        onClick={() => handleUnlockClue(clue.id)}
                        disabled={isBusy}
                      >
                        {isBusy ? (
                          <span>Analyzing Layer...</span>
                        ) : (
                          <>
                            <Lock size={13} />
                            <span>Analyze Clue (+{clue.xp_reward} XP)</span>
                          </>
                        )}
                      </button>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Tab: Root Cause & Technical Profile */}
      {activeTab === 'rca' && (
        <div className="tab-content">
          <div className="rca-grid">
            <div className="rca-card highlight-card">
              <span className="rca-label">ROOT CAUSE ANALYSIS</span>
              <h2 className="rca-title">{incident.root_cause || 'Root cause under investigation.'}</h2>
              <div className="rca-section">
                <span className="rca-subtitle">Remediation & Proposed Fix</span>
                <p className="rca-text">{incident.solution || 'Remediation steps not yet documented.'}</p>
              </div>
            </div>

            <div className="rca-card">
              <span className="rca-label">TECHNICAL PROFILE</span>
              <div className="profile-spec-grid">
                <div className="spec-item">
                  <span className="spec-label">Language</span>
                  <span className="spec-val">{incident.language || 'N/A'}</span>
                </div>
                <div className="spec-item">
                  <span className="spec-label">Framework</span>
                  <span className="spec-val">{incident.framework || 'N/A'}</span>
                </div>
                <div className="spec-item">
                  <span className="spec-label">Environment</span>
                  <span className="spec-val">{incident.environment || 'Production'}</span>
                </div>
                <div className="spec-item">
                  <span className="spec-label">Category</span>
                  <span className="spec-val">{incident.category || 'Backend'}</span>
                </div>
              </div>

              {incident.tags && (
                <div className="tags-section">
                  <span className="spec-label">Search Index Tags</span>
                  <div className="tags-container">
                    {incident.tags
                      .split(',')
                      .map((t) => t.trim())
                      .filter(Boolean)
                      .map((tag) => (
                        <span key={tag} className="tag-pill">
                          #{tag}
                        </span>
                      ))}
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Tab: Discussion / Field Log */}
      {activeTab === 'discussion' && (
        <div className="tab-content">
          <div className="comments-layout">
            <div className="comments-list">
              {comments.length > 0 ? (
                comments.map((comm) => (
                  <div key={comm.id} className="comment-item">
                    <div className="comment-avatar">
                      {comm.name ? comm.name[0].toUpperCase() : 'U'}
                    </div>
                    <div className="comment-body">
                      <div className="comment-meta">
                        <span className="comment-author">{comm.name}</span>
                        <span className="comment-time">
                          <Clock size={11} /> {comm.created_at}
                        </span>
                      </div>
                      <p className="comment-content">{comm.content}</p>
                    </div>
                  </div>
                ))
              ) : (
                <div className="empty-state-compact">
                  <MessageSquare size={24} className="empty-icon" />
                  <p className="empty-text">No investigation notes recorded yet. Add the first entry below.</p>
                </div>
              )}
            </div>

            {/* Add note form */}
            <form className="comment-form" onSubmit={handleAddComment}>
              <label className="form-label" htmlFor="comment-input">
                Add Field Note / Investigation Finding
              </label>
              <textarea
                id="comment-input"
                className="form-textarea"
                rows={3}
                placeholder="Document your findings, hypothesis, or reproduction steps..."
                value={newComment}
                onChange={(e) => setNewComment(e.target.value)}
                maxLength={1000}
                required
              />
              <div className="form-action-row">
                <span className="char-count">{1000 - newComment.length} chars left</span>
                <button
                  type="submit"
                  className="btn btn-primary btn-sm"
                  disabled={isPostingComment || !newComment.trim()}
                >
                  <Send size={13} />
                  <span>{isPostingComment ? 'Posting...' : 'Post Note'}</span>
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Tab: Postmortem Report */}
      {activeTab === 'postmortem' && (
        <div className="tab-content">
          <div className="postmortem-card">
            <div className="postmortem-header">
              <div>
                <span className="postmortem-eyebrow">AUTOMATED POSTMORTEM REPORT</span>
                <h2 className="postmortem-title">INC-{String(incident.id).padStart(3, '0')} Engineering Postmortem</h2>
                <p className="postmortem-subtitle">
                  Ready-to-publish postmortem summarizing impact, isolated telemetry, root cause, and remediation plan.
                </p>
              </div>

              <div className="postmortem-actions">
                <button
                  type="button"
                  className="btn btn-secondary btn-sm"
                  onClick={handleCopyPostmortem}
                >
                  {postmortemCopied ? <Check size={14} /> : <Copy size={14} />}
                  <span>{postmortemCopied ? 'Copied Markdown!' : 'Copy Markdown'}</span>
                </button>
                <button
                  type="button"
                  className="btn btn-primary btn-sm"
                  onClick={handleDownloadPostmortem}
                >
                  <Download size={14} />
                  <span>Download (.md)</span>
                </button>
              </div>
            </div>

            <div className="postmortem-preview-body">
              <pre className="postmortem-code">{generatePostmortemMarkdown()}</pre>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
