import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import Database from 'better-sqlite3';
import http from 'http';
import { Server } from 'socket.io';
import path from 'path';

const app=express(); const server=http.createServer(app); const io=new Server(server,{cors:{origin:'http://localhost:5173'}});
app.use(cors({origin:'http://localhost:5173'})); app.use(express.json());
const PORT=process.env.PORT||5000; const SECRET=process.env.JWT_SECRET||'bugatlas-dev-secret';
const db=new Database(path.join(process.cwd(),'bugatlas.db')); db.pragma('journal_mode=WAL');
db.exec(`
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT DEFAULT 'DETECTIVE',xp INTEGER DEFAULT 0,level INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS cases(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,description TEXT NOT NULL,severity TEXT NOT NULL,status TEXT DEFAULT 'OPEN',environment TEXT DEFAULT 'Production',category TEXT DEFAULT 'Backend',language TEXT,framework TEXT,root_cause TEXT,solution TEXT,tags TEXT,created_by INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS clues(id INTEGER PRIMARY KEY AUTOINCREMENT,case_id INTEGER,title TEXT NOT NULL,description TEXT NOT NULL,evidence TEXT NOT NULL,xp_reward INTEGER DEFAULT 20,order_no INTEGER,FOREIGN KEY(case_id) REFERENCES cases(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS progress(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,case_id INTEGER,clue_id INTEGER,unlocked_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(user_id,clue_id));
CREATE TABLE IF NOT EXISTS comments(id INTEGER PRIMARY KEY AUTOINCREMENT,case_id INTEGER,user_id INTEGER,content TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
`);
const pub=u=>({id:u.id,name:u.name,email:u.email,role:u.role,xp:u.xp,level:u.level});
const level=x=>Math.floor(x/500)+1;
const seed=()=>{if(db.prepare('SELECT COUNT(*) c FROM users').get().c)return; const u=db.prepare('INSERT INTO users(name,email,password_hash,role,xp,level) VALUES(?,?,?,?,?,?)');u.run('Shreya','shreya@bugatlas.dev',bcrypt.hashSync('shreya123',10),'DETECTIVE',460,1);u.run('Admin','admin@bugatlas.dev',bcrypt.hashSync('admin123',10),'ADMIN',1450,3);
const c=db.prepare('INSERT INTO cases(title,description,severity,status,environment,category,language,framework,root_cause,solution,tags,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');
const a=c.run('JWT Session Ghosts','Authenticated users are silently kicked out after a successful login when the access token reaches its short lifetime.','CRITICAL','INVESTIGATING','Production','SECURITY','Java','Spring Boot','Token lifetime mismatch','Add refresh-token rotation and validate expiry consistently across services.','jwt,auth,security,session',2).lastInsertRowid;
const b=c.run('Payment Timeout Cascade','Checkout becomes unreliable when a payment provider slows down; retries create a second wave of traffic.','HIGH','OPEN','Production','PERFORMANCE','JavaScript','Node.js','No request deadline','Use explicit timeouts, bounded retries and circuit breaking.','payment,timeout,retry,api',2).lastInsertRowid;
const d=c.run('Dashboard Listener Leak','A long-running dashboard tab consumes more memory after repeated navigation.','MEDIUM','RESOLVED','Staging','FRONTEND','TypeScript','React','Effect cleanup missing','Remove event listeners on unmount and avoid duplicate subscriptions.','react,memory,events,leak',2).lastInsertRowid;
const add=db.prepare('INSERT INTO clues(case_id,title,description,evidence,xp_reward,order_no) VALUES(?,?,?,?,?,?)');
[[a,'The timestamp mismatch','Compare the token issued time with the client session timer.','iat: 02:40:11\\nexp: 03:10:11\\nclient refresh: never',25,1],[a,'The silent refresh','The API exposes refresh-token support but the client has no refresh interceptor.','POST /auth/refresh → never called\\n401 → logout',35,2],[a,'The clock drift','Production nodes disagree by 41 seconds, making expiry failures look random.','node-a clock: 03:10:10\\nnode-b clock: 03:10:51',45,3], [b,'The slow provider','The payment provider occasionally takes longer than the UX budget.','POST /charge\\nTTFB: 10.8s\\nstatus: 200',20,1],[b,'The missing deadline','The HTTP wrapper waits forever for a response.','timeout: undefined\\nabort controller: absent',30,2],[b,'The retry storm','Three retries multiply load while the provider is already degraded.','attempts: 1 → 2 → 4\\nqueue depth: +187%',50,3],[d,'The repeated listener','Each mount registers another resize handler.','resize listeners: 1 → 4 → 9',20,1],[d,'The missing cleanup','The effect has no teardown function.','useEffect(() => addEventListener(...))\\ncleanup: undefined',30,2],[d,'The heap fingerprint','Detached handlers remain reachable after navigation.','Detached listeners: 9\\nretained heap: 4.8 MB',50,3]].forEach(x=>add.run(...x));}; seed();
function auth(req,res,next){const h=req.headers.authorization;if(!h?.startsWith('Bearer '))return res.status(401).json({message:'Authentication required'});try{req.user=jwt.verify(h.slice(7),SECRET);next()}catch{return res.status(401).json({message:'Invalid or expired token'})}}
function admin(req,res,next){if(req.user.role!=='ADMIN')return res.status(403).json({message:'Admin only'});next()}
app.get('/api/health',(q,r)=>r.json({ok:true,service:'BugAtlas API'}));
app.post('/api/auth/register',(req,res)=>{const {name,email,password}=req.body;if(!name||!email||!password)return res.status(400).json({message:'All fields are required'});try{const x=db.prepare('INSERT INTO users(name,email,password_hash) VALUES(?,?,?)').run(name,email,bcrypt.hashSync(password,10));const u=db.prepare('SELECT * FROM users WHERE id=?').get(x.lastInsertRowid);const token=jwt.sign({id:u.id,role:u.role},SECRET,{expiresIn:'7d'});res.status(201).json({token,user:pub(u)})}catch{res.status(409).json({message:'Email already registered'})}});
app.post('/api/auth/login',(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE email=?').get(req.body.email);if(!u||!bcrypt.compareSync(req.body.password||'',u.password_hash))return res.status(401).json({message:'Invalid credentials'});const token=jwt.sign({id:u.id,role:u.role},SECRET,{expiresIn:'7d'});res.json({token,user:pub(u)})});
app.get('/api/auth/me',auth,(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE id=?').get(req.user.id);res.json({user:pub(u)})});
app.get('/api/cases',auth,(req,res)=>{const rows=db.prepare(`SELECT c.*,COUNT(cl.id) clue_count FROM cases c LEFT JOIN clues cl ON cl.case_id=c.id GROUP BY c.id ORDER BY c.id DESC`).all();res.json({cases:rows})});
app.get('/api/cases/:id',auth,(req,res)=>{const id=+req.params.id,c=db.prepare('SELECT * FROM cases WHERE id=?').get(id);if(!c)return res.status(404).json({message:'Case not found'});const clues=db.prepare('SELECT id,title,description,xp_reward,order_no FROM clues WHERE case_id=? ORDER BY order_no').all(id);const found=db.prepare('SELECT clue_id FROM progress WHERE user_id=? AND case_id=?').all(req.user.id,id).map(x=>x.clue_id);const full=clues.map(x=>found.includes(x.id)?{...x,evidence:db.prepare('SELECT evidence FROM clues WHERE id=?').get(x.id).evidence}:{...x});const comments=db.prepare('SELECT comments.*,users.name FROM comments JOIN users ON users.id=comments.user_id WHERE case_id=? ORDER BY comments.id DESC').all(id);res.json({case:c,clues:full,found,comments})});
app.post('/api/cases',auth,(req,res)=>{const {title,description,severity='HIGH',environment='Production',category='Backend',language='JavaScript',framework='Node.js',root_cause='',solution='',tags='',clues=[]}=req.body;if(!title||!description)return res.status(400).json({message:'Title and description required'});const tx=db.transaction(()=>{const x=db.prepare('INSERT INTO cases(title,description,severity,environment,category,language,framework,root_cause,solution,tags,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(title,description,severity,environment,category,language,framework,root_cause,solution,tags,req.user.id);const add=db.prepare('INSERT INTO clues(case_id,title,description,evidence,xp_reward,order_no) VALUES(?,?,?,?,?,?)');clues.forEach((z,i)=>add.run(x.lastInsertRowid,z.title,z.description,z.evidence||'Evidence pending',+z.xp_reward||20,i+1));return x.lastInsertRowid});const id=tx();io.emit('case:created',{id,title});res.status(201).json({id})});
app.post('/api/cases/:caseId/clues/:clueId/unlock',auth,(req,res)=>{const caseId=+req.params.caseId,clueId=+req.params.clueId,z=db.prepare('SELECT * FROM clues WHERE id=? AND case_id=?').get(clueId,caseId);if(!z)return res.status(404).json({message:'Clue not found'});try{db.prepare('INSERT INTO progress(user_id,case_id,clue_id) VALUES(?,?,?)').run(req.user.id,caseId,clueId);const u=db.prepare('SELECT * FROM users WHERE id=?').get(req.user.id),newXp=u.xp+z.xp_reward;db.prepare('UPDATE users SET xp=?,level=? WHERE id=?').run(newXp,level(newXp),u.id);res.json({xp:newXp,level:level(newXp),reward:z.xp_reward})}catch{res.status(409).json({message:'Already unlocked'})}});
app.post('/api/cases/:id/comments',auth,(req,res)=>{if(!req.body.content?.trim())return res.status(400).json({message:'Comment required'});db.prepare('INSERT INTO comments(case_id,user_id,content) VALUES(?,?,?)').run(+req.params.id,req.user.id,req.body.content.trim());res.status(201).json({ok:true})});
app.get('/api/leaderboard',auth,(req,res)=>res.json({leaderboard:db.prepare('SELECT id,name,xp,level FROM users ORDER BY xp DESC LIMIT 20').all()}));
app.get('/api/stats',auth,(req,res)=>{const total=db.prepare('SELECT COUNT(*) c FROM cases').get().c;const critical=db.prepare("SELECT COUNT(*) c FROM cases WHERE severity='CRITICAL'").get().c;const resolved=db.prepare("SELECT COUNT(*) c FROM cases WHERE status='RESOLVED'").get().c;const clues=db.prepare('SELECT COUNT(*) c FROM clues').get().c;const cats=db.prepare('SELECT category,COUNT(*) count FROM cases GROUP BY category').all();res.json({total,critical,resolved,clues,categories:cats})});
app.get('/api/achievements',auth,(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE id=?').get(req.user.id),n=db.prepare('SELECT COUNT(*) c FROM progress WHERE user_id=?').get(u.id).c;res.json({achievements:[['FIRST CLUE','Unlock your first clue.',n>=1],['EVIDENCE HUNTER','Discover 5 clues.',n>=5],['ROOT CAUSE','Reach 500 XP.',u.xp>=500],['SYSTEM THINKER','Reach level 3.',u.level>=3],['LEGEND','Reach 2000 XP.',u.xp>=2000]].map((x,i)=>({id:i+1,title:x[0],description:x[1],unlocked:x[2]}))})});
app.delete('/api/cases/:id',auth,admin,(req,res)=>{db.prepare('DELETE FROM cases WHERE id=?').run(+req.params.id);res.json({ok:true})});
io.on('connection',s=>s.emit('system:ready',{ok:true}));server.listen(PORT,()=>console.log(`BugAtlas API → http://localhost:${PORT}`));
