import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import Database from 'better-sqlite3';
import http from 'http';
import { Server } from 'socket.io';
import path from 'path';

const app=express();
const server=http.createServer(app);
const allowed=(process.env.CLIENT_ORIGIN||'http://localhost:5173').split(',').map(x=>x.trim()).filter(Boolean);
const io=new Server(server,{cors:{origin:allowed,methods:['GET','POST','DELETE','OPTIONS']}});
app.use(cors({origin:(origin,cb)=>!origin||allowed.includes(origin)?cb(null,true):cb(new Error('CORS blocked'))}));
app.use(express.json({limit:'200kb'}));
const PORT=Number(process.env.PORT||5000);const SECRET=process.env.JWT_SECRET||'bugatlas-dev-secret-change-me';
const db=new Database(path.join(process.cwd(),'bugatlas.db'));db.pragma('journal_mode=WAL');db.pragma('foreign_keys=ON');
db.exec(`
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT DEFAULT 'DETECTIVE',xp INTEGER DEFAULT 0,level INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS cases(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,description TEXT NOT NULL,severity TEXT NOT NULL,status TEXT DEFAULT 'OPEN',environment TEXT DEFAULT 'Production',category TEXT DEFAULT 'Backend',language TEXT,framework TEXT,root_cause TEXT,solution TEXT,tags TEXT,created_by INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS clues(id INTEGER PRIMARY KEY AUTOINCREMENT,case_id INTEGER NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL,evidence TEXT NOT NULL,xp_reward INTEGER DEFAULT 20,order_no INTEGER,FOREIGN KEY(case_id) REFERENCES cases(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS progress(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,case_id INTEGER NOT NULL,clue_id INTEGER NOT NULL,unlocked_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(user_id,clue_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(case_id) REFERENCES cases(id) ON DELETE CASCADE,FOREIGN KEY(clue_id) REFERENCES clues(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS comments(id INTEGER PRIMARY KEY AUTOINCREMENT,case_id INTEGER NOT NULL,user_id INTEGER NOT NULL,content TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(case_id) REFERENCES cases(id) ON DELETE CASCADE,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
`);
const pub=u=>({id:u.id,name:u.name,email:u.email,role:u.role,xp:u.xp,level:u.level});
const calcLevel=x=>Math.floor(x/500)+1;
function seed(){if(db.prepare('SELECT COUNT(*) c FROM users').get().c)return;const u=db.prepare('INSERT INTO users(name,email,password_hash,role,xp,level) VALUES(?,?,?,?,?,?)');u.run('Shreya','shreya@bugatlas.dev',bcrypt.hashSync('shreya123',10),'DETECTIVE',460,1);u.run('Admin','admin@bugatlas.dev',bcrypt.hashSync('admin123',10),'ADMIN',1450,3);const c=db.prepare('INSERT INTO cases(title,description,severity,status,environment,category,language,framework,root_cause,solution,tags,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');const a=c.run('JWT Session Ghosts','Authenticated users are silently kicked out after a successful login when the access token reaches its short lifetime.','CRITICAL','INVESTIGATING','Production','SECURITY','Java','Spring Boot','Token lifetime mismatch','Add refresh-token rotation and validate expiry consistently across services.','jwt,auth,security,session',2).lastInsertRowid;const b=c.run('Payment Timeout Cascade','Checkout becomes unreliable when a payment provider slows down; retries create a second wave of traffic.','HIGH','OPEN','Production','PERFORMANCE','JavaScript','Node.js','No request deadline','Use explicit timeouts, bounded retries and circuit breaking.','payment,timeout,retry,api',2).lastInsertRowid;const d=c.run('Dashboard Listener Leak','A long-running dashboard tab consumes more memory after repeated navigation.','MEDIUM','RESOLVED','Staging','FRONTEND','TypeScript','React','Effect cleanup missing','Remove event listeners on unmount and avoid duplicate subscriptions.','react,memory,events,leak',2).lastInsertRowid;const add=db.prepare('INSERT INTO clues(case_id,title,description,evidence,xp_reward,order_no) VALUES(?,?,?,?,?,?)');[[a,'The timestamp mismatch','Compare the token issued time with the client session timer','iat: 02:40:11\nexp: 03:10:11\nclient refresh: never',25,1],[a,'The silent refresh','The API exposes refresh-token support but the client has no refresh interceptor','POST /auth/refresh → never called\n401 → logout',35,2],[a,'The clock drift','Production nodes disagree by 41 seconds, making expiry failures look random','node-a clock: 03:10:10\nnode-b clock: 03:10:51',45,3],[b,'The slow provider','The payment provider occasionally takes longer than the UX budget','POST /charge\nTTFB: 10.8s\nstatus: 200',20,1],[b,'The missing deadline','The HTTP wrapper waits forever for a response','timeout: undefined\nabort controller: absent',30,2],[b,'The retry storm','Three retries multiply load while the provider is already degraded','attempts: 1 → 2 → 4\nqueue depth: +187%',50,3],[d,'The repeated listener','Each mount registers another resize handler','resize listeners: 1 → 4 → 9',20,1],[d,'The missing cleanup','The effect has no teardown function','useEffect(() => addEventListener(...))\ncleanup: undefined',30,2],[d,'The heap fingerprint','Detached handlers remain reachable after navigation','Detached listeners: 9\nretained heap: 4.8 MB',50,3]].forEach(x=>add.run(...x));}
seed();
function auth(req,res,next){const h=req.headers.authorization;if(!h?.startsWith('Bearer '))return res.status(401).json({message:'Authentication required'});try{req.user=jwt.verify(h.slice(7),SECRET);next()}catch{return res.status(401).json({message:'Invalid or expired token'})}}
function admin(req,res,next){if(req.user.role!=='ADMIN')return res.status(403).json({message:'Admin only'});next()}
const cleanEmail=e=>String(e||'').trim().toLowerCase();
app.get('/api/health',(q,r)=>r.json({ok:true,service:'BugAtlas API',time:new Date().toISOString()}));
app.post('/api/auth/register',(req,res)=>{const name=String(req.body.name||'').trim(),email=cleanEmail(req.body.email),password=String(req.body.password||'');if(name.length<2||!email||password.length<6)return res.status(400).json({message:'Name, valid email and 6+ character password are required'});try{const x=db.prepare('INSERT INTO users(name,email,password_hash) VALUES(?,?,?)').run(name,email,bcrypt.hashSync(password,10));const u=db.prepare('SELECT * FROM users WHERE id=?').get(x.lastInsertRowid);const token=jwt.sign({id:u.id,role:u.role},SECRET,{expiresIn:'7d'});res.status(201).json({token,user:pub(u)})}catch(e){res.status(409).json({message:'Email already registered'})}});
app.post('/api/auth/login',(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE email=?').get(cleanEmail(req.body.email));if(!u||!bcrypt.compareSync(String(req.body.password||''),u.password_hash))return res.status(401).json({message:'Invalid credentials'});const token=jwt.sign({id:u.id,role:u.role},SECRET,{expiresIn:'7d'});res.json({token,user:pub(u)})});
app.get('/api/auth/me',auth,(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE id=?').get(req.user.id);if(!u)return res.status(401).json({message:'User not found'});res.json({user:pub(u)})});
app.get('/api/cases',auth,(req,res)=>{const rows=db.prepare(`SELECT c.*,COUNT(cl.id) clue_count FROM cases c LEFT JOIN clues cl ON cl.case_id=c.id GROUP BY c.id ORDER BY c.id DESC`).all();res.json({cases:rows})});
app.get('/api/cases/:id',auth,(req,res)=>{const id=Number(req.params.id);if(!Number.isInteger(id))return res.status(400).json({message:'Invalid case id'});const c=db.prepare('SELECT * FROM cases WHERE id=?').get(id);if(!c)return res.status(404).json({message:'Case not found'});const clues=db.prepare('SELECT id,title,description,xp_reward,order_no FROM clues WHERE case_id=? ORDER BY order_no').all(id);const found=db.prepare('SELECT clue_id FROM progress WHERE user_id=? AND case_id=?').all(req.user.id,id).map(x=>x.clue_id);const full=clues.map(x=>found.includes(x.id)?{...x,evidence:db.prepare('SELECT evidence FROM clues WHERE id=?').get(x.id).evidence}:{...x});const comments=db.prepare('SELECT comments.id,comments.content,comments.created_at,users.name FROM comments JOIN users ON users.id=comments.user_id WHERE case_id=? ORDER BY comments.id DESC').all(id);res.json({case:c,clues:full,found,comments})});
app.post('/api/cases',auth,(req,res)=>{const b=req.body||{},title=String(b.title||'').trim(),description=String(b.description||'').trim();if(!title||!description)return res.status(400).json({message:'Title and description required'});const clues=Array.isArray(b.clues)?b.clues.slice(0,10):[];const tx=db.transaction(()=>{const x=db.prepare('INSERT INTO cases(title,description,severity,environment,category,language,framework,root_cause,solution,tags,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(title,description,['CRITICAL','HIGH','MEDIUM','LOW'].includes(b.severity)?b.severity:'HIGH',String(b.environment||'Production').slice(0,80),String(b.category||'Backend').slice(0,80),String(b.language||'JavaScript').slice(0,80),String(b.framework||'Node.js').slice(0,80),String(b.root_cause||'').slice(0,500),String(b.solution||'').slice(0,1000),String(b.tags||'').slice(0,500),req.user.id);const add=db.prepare('INSERT INTO clues(case_id,title,description,evidence,xp_reward,order_no) VALUES(?,?,?,?,?,?)');clues.forEach((z,i)=>{const t=String(z?.title||`Clue ${i+1}`).slice(0,120),d=String(z?.description||'Investigate the evidence').slice(0,500),ev=String(z?.evidence||'Evidence pending').slice(0,2000),xp=Math.min(100,Math.max(5,Number(z?.xp_reward)||20));add.run(x.lastInsertRowid,t,d,ev,xp,i+1)});return x.lastInsertRowid});const id=tx();io.emit('case:created',{id,title});res.status(201).json({id})});
app.post('/api/cases/:caseId/clues/:clueId/unlock',auth,(req,res)=>{const caseId=Number(req.params.caseId),clueId=Number(req.params.clueId);const z=db.prepare('SELECT * FROM clues WHERE id=? AND case_id=?').get(clueId,caseId);if(!z)return res.status(404).json({message:'Clue not found'});try{const tx=db.transaction(()=>{db.prepare('INSERT INTO progress(user_id,case_id,clue_id) VALUES(?,?,?)').run(req.user.id,caseId,clueId);const u=db.prepare('SELECT * FROM users WHERE id=?').get(req.user.id),newXp=u.xp+z.xp_reward,newLevel=calcLevel(newXp);db.prepare('UPDATE users SET xp=?,level=? WHERE id=?').run(newXp,newLevel,u.id);return{newXp,newLevel}});const out=tx();res.json({xp:out.newXp,level:out.newLevel,reward:z.xp_reward})}catch(e){res.status(409).json({message:'Already unlocked'})}});
app.post('/api/cases/:id/comments',auth,(req,res)=>{const id=Number(req.params.id),content=String(req.body.content||'').trim();if(!Number.isInteger(id)||!content||content.length>1000)return res.status(400).json({message:'Valid comment up to 1000 characters is required'});if(!db.prepare('SELECT 1 FROM cases WHERE id=?').get(id))return res.status(404).json({message:'Case not found'});const x=db.prepare('INSERT INTO comments(case_id,user_id,content) VALUES(?,?,?)').run(id,req.user.id,content);res.status(201).json({ok:true,id:x.lastInsertRowid})});
app.get('/api/leaderboard',auth,(req,res)=>res.json({leaderboard:db.prepare('SELECT id,name,xp,level FROM users ORDER BY xp DESC,id ASC LIMIT 20').all()}));
app.get('/api/stats',auth,(req,res)=>{const total=db.prepare('SELECT COUNT(*) c FROM cases').get().c,critical=db.prepare("SELECT COUNT(*) c FROM cases WHERE severity='CRITICAL'").get().c,resolved=db.prepare("SELECT COUNT(*) c FROM cases WHERE status='RESOLVED'").get().c,clues=db.prepare('SELECT COUNT(*) c FROM clues').get().c,categories=db.prepare('SELECT category,COUNT(*) count FROM cases GROUP BY category ORDER BY count DESC').all();res.json({total,critical,resolved,clues,categories})});
app.get('/api/achievements',auth,(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE id=?').get(req.user.id),n=db.prepare('SELECT COUNT(*) c FROM progress WHERE user_id=?').get(u.id).c;res.json({achievements:[['FIRST CLUE','Unlock your first clue.',n>=1],['EVIDENCE HUNTER','Discover 5 clues.',n>=5],['ROOT CAUSE','Reach 500 XP.',u.xp>=500],['SYSTEM THINKER','Reach level 3.',u.level>=3],['LEGEND','Reach 2000 XP.',u.xp>=2000]].map((x,i)=>({id:i+1,title:x[0],description:x[1],unlocked:x[2]}))})});
app.delete('/api/cases/:id',auth,admin,(req,res)=>{const id=Number(req.params.id);const x=db.prepare('DELETE FROM cases WHERE id=?').run(id);if(!x.changes)return res.status(404).json({message:'Case not found'});res.json({ok:true})});
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({message:'Internal server error'})});
io.on('connection',s=>s.emit('system:ready',{ok:true}));
server.listen(PORT,()=>console.log(`BugAtlas API → http://localhost:${PORT}`));
